@startuml
set namespaceSeparator ::

abstract class "project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" {
}

class "project_ii::blocs::booking_page_bloc.dart::NextStepEvent" {
  +BuildContext context
}

"project_ii::blocs::booking_page_bloc.dart::NextStepEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::NextStepEvent"

class "project_ii::blocs::booking_page_bloc.dart::BackStepEvent" {
}

"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::BackStepEvent"

class "project_ii::blocs::booking_page_bloc.dart::PickImageEvent" {
  +Uint8List? bytes
}

"project_ii::blocs::booking_page_bloc.dart::PickImageEvent" o-- "dart::typed_data::Uint8List"
"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::PickImageEvent"

class "project_ii::blocs::booking_page_bloc.dart::RequireDataEvent" {
}

"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::RequireDataEvent"

class "project_ii::blocs::booking_page_bloc.dart::CompleteRenderEvent" {
}

"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::CompleteRenderEvent"

class "project_ii::blocs::booking_page_bloc.dart::RefreshEvent" {
}

"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::RefreshEvent"

class "project_ii::blocs::booking_page_bloc.dart::ModifyOwnerEvent" {
  +String? name
  +String? tel
  +String? gender
}

"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::ModifyOwnerEvent"

class "project_ii::blocs::booking_page_bloc.dart::ModifyCatEvent" {
  +String? weightRank
  +String? name
  +String? species
  +String? physicalCondition
  +String? appearance
  +String? gender
  +Uint8List? image
  +int? age
  +int? sterilization
  +int? vaccination
  +double? weight
}

"project_ii::blocs::booking_page_bloc.dart::ModifyCatEvent" o-- "dart::typed_data::Uint8List"
"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::ModifyCatEvent"

class "project_ii::blocs::booking_page_bloc.dart::ModifyOrderEvent" {
  +List<Addition>? additionsList
  +DateTime? checkIn
  +DateTime? checkOut
  +String? attention
  +String? note
  +String? roomID
  +int? eatingRank
  +int? subRoomNum
}

"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::ModifyOrderEvent"

class "project_ii::blocs::booking_page_bloc.dart::SubmitDataEvent" {
  +BuildContext context
}

"project_ii::blocs::booking_page_bloc.dart::SubmitDataEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::booking_page_bloc.dart::BookingPageEvent" <|-- "project_ii::blocs::booking_page_bloc.dart::SubmitDataEvent"

class "project_ii::blocs::booking_page_bloc.dart::BookingState" {
  +GlobalKey<FormState> formKey1
  +GlobalKey<FormState> formKey2
  +GlobalKey<FormState> formKey3
  +Order order
  +RenderState renderState
  +int currentStep
  +List<Object?> props
  +BookingState copyWith()
  +Order modifyOrder()
  +Cat modifyCat()
  +Owner modifyOwner()
}

"project_ii::blocs::booking_page_bloc.dart::BookingState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"project_ii::blocs::booking_page_bloc.dart::BookingState" o-- "project_ii::model::order_model.dart::Order"
"project_ii::blocs::booking_page_bloc.dart::BookingState" o-- "project_ii::data::types::render_state.dart::RenderState"
"equatable::src::equatable.dart::Equatable" <|-- "project_ii::blocs::booking_page_bloc.dart::BookingState"

class "project_ii::blocs::booking_page_bloc.dart::BookingPageBloc" {
  +void onTransition()
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::blocs::booking_page_bloc.dart::BookingPageBloc"

abstract class "project_ii::blocs::calendar_page_bloc.dart::CalendarPageEvent" {
}

class "project_ii::blocs::calendar_page_bloc.dart::IncreaseMonthEvent" {
}

"project_ii::blocs::calendar_page_bloc.dart::CalendarPageEvent" <|-- "project_ii::blocs::calendar_page_bloc.dart::IncreaseMonthEvent"

class "project_ii::blocs::calendar_page_bloc.dart::DecreaseMonthEvent" {
}

"project_ii::blocs::calendar_page_bloc.dart::CalendarPageEvent" <|-- "project_ii::blocs::calendar_page_bloc.dart::DecreaseMonthEvent"

class "project_ii::blocs::calendar_page_bloc.dart::ChangeGuestListDayEvent" {
  +int? dayForGuestList
}

"project_ii::blocs::calendar_page_bloc.dart::CalendarPageEvent" <|-- "project_ii::blocs::calendar_page_bloc.dart::ChangeGuestListDayEvent"

class "project_ii::blocs::calendar_page_bloc.dart::CompleteRenderEvent" {
}

"project_ii::blocs::calendar_page_bloc.dart::CalendarPageEvent" <|-- "project_ii::blocs::calendar_page_bloc.dart::CompleteRenderEvent"

class "project_ii::blocs::calendar_page_bloc.dart::PrintGuestListEvent" {
}

"project_ii::blocs::calendar_page_bloc.dart::CalendarPageEvent" <|-- "project_ii::blocs::calendar_page_bloc.dart::PrintGuestListEvent"

class "project_ii::blocs::calendar_page_bloc.dart::RequireDataEvent" {
}

"project_ii::blocs::calendar_page_bloc.dart::CalendarPageEvent" <|-- "project_ii::blocs::calendar_page_bloc.dart::RequireDataEvent"

class "project_ii::blocs::calendar_page_bloc.dart::GotoInfoPageEvent" {
  +int oidx
  +int ridx
  +BuildContext context
}

"project_ii::blocs::calendar_page_bloc.dart::GotoInfoPageEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::calendar_page_bloc.dart::CalendarPageEvent" <|-- "project_ii::blocs::calendar_page_bloc.dart::GotoInfoPageEvent"

class "project_ii::blocs::calendar_page_bloc.dart::RefreshEvent" {
}

"project_ii::blocs::calendar_page_bloc.dart::CalendarPageEvent" <|-- "project_ii::blocs::calendar_page_bloc.dart::RefreshEvent"

class "project_ii::blocs::calendar_page_bloc.dart::CalendarState" {
  +DateTime currentMonth
  +DateTime today
  +int dayForGuestList
  +RenderState state
  +List<Object?> props
  +CalendarState copyWith()
}

"project_ii::blocs::calendar_page_bloc.dart::CalendarState" o-- "project_ii::data::types::render_state.dart::RenderState"
"equatable::src::equatable.dart::Equatable" <|-- "project_ii::blocs::calendar_page_bloc.dart::CalendarState"

class "project_ii::blocs::calendar_page_bloc.dart::CalendarPageBloc" {
  +void onTransition()
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::blocs::calendar_page_bloc.dart::CalendarPageBloc"
"project_ii::data::generators::excel_generator.dart::ExcelGenerator" <|-- "project_ii::blocs::calendar_page_bloc.dart::CalendarPageBloc"

abstract class "project_ii::blocs::history_page_bloc.dart::HistoryPageEvent" {
}

class "project_ii::blocs::history_page_bloc.dart::RequireDataEvent" {
}

"project_ii::blocs::history_page_bloc.dart::HistoryPageEvent" <|-- "project_ii::blocs::history_page_bloc.dart::RequireDataEvent"

class "project_ii::blocs::history_page_bloc.dart::CompleteRenderEvent" {
}

"project_ii::blocs::history_page_bloc.dart::HistoryPageEvent" <|-- "project_ii::blocs::history_page_bloc.dart::CompleteRenderEvent"

class "project_ii::blocs::history_page_bloc.dart::RefreshEvent" {
}

"project_ii::blocs::history_page_bloc.dart::HistoryPageEvent" <|-- "project_ii::blocs::history_page_bloc.dart::RefreshEvent"

class "project_ii::blocs::history_page_bloc.dart::HistoryState" {
  +RenderState renderState
  +List<Object?> props
  +HistoryState copyWith()
}

"project_ii::blocs::history_page_bloc.dart::HistoryState" o-- "project_ii::data::types::render_state.dart::RenderState"
"equatable::src::equatable.dart::Equatable" <|-- "project_ii::blocs::history_page_bloc.dart::HistoryState"

class "project_ii::blocs::history_page_bloc.dart::HistoryPageBloc" {
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::blocs::history_page_bloc.dart::HistoryPageBloc"

abstract class "project_ii::blocs::home_page_bloc.dart::HomePageEvent" {
}

class "project_ii::blocs::home_page_bloc.dart::ChangeTabEvent" {
  +int selectedIndex
  +FocusNode? primaryFocus
}

"project_ii::blocs::home_page_bloc.dart::ChangeTabEvent" o-- "flutter::src::widgets::focus_manager.dart::FocusNode"
"project_ii::blocs::home_page_bloc.dart::HomePageEvent" <|-- "project_ii::blocs::home_page_bloc.dart::ChangeTabEvent"

class "project_ii::blocs::home_page_bloc.dart::LogoutEvent" {
  +BuildContext context
}

"project_ii::blocs::home_page_bloc.dart::LogoutEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::home_page_bloc.dart::HomePageEvent" <|-- "project_ii::blocs::home_page_bloc.dart::LogoutEvent"

class "project_ii::blocs::home_page_bloc.dart::RequireDataEvent" {
}

"project_ii::blocs::home_page_bloc.dart::HomePageEvent" <|-- "project_ii::blocs::home_page_bloc.dart::RequireDataEvent"

class "project_ii::blocs::home_page_bloc.dart::HomeState" {
  +List<Widget Function(BuildContext)> builders
  +int selectedIndex
  +String infoString
  {static} +List<Widget Function(BuildContext)> builderCalls
  +List<Object?> props
  +HomeState copyWith()
}

"equatable::src::equatable.dart::Equatable" <|-- "project_ii::blocs::home_page_bloc.dart::HomeState"

class "project_ii::blocs::home_page_bloc.dart::HomePageBloc" {
  +void onTransition()
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::blocs::home_page_bloc.dart::HomePageBloc"

abstract class "project_ii::blocs::info_page_bloc.dart::InformationPageEvent" {
}

class "project_ii::blocs::info_page_bloc.dart::ToggleModifyOwnerEvent" {
}

"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::ToggleModifyOwnerEvent"

class "project_ii::blocs::info_page_bloc.dart::ToggleModifyCatEvent" {
}

"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::ToggleModifyCatEvent"

class "project_ii::blocs::info_page_bloc.dart::ToggleModifyOrderEvent" {
}

"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::ToggleModifyOrderEvent"

class "project_ii::blocs::info_page_bloc.dart::ModifyOwnerEvent" {
  +String? name
  +String? tel
  +String? gender
}

"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::ModifyOwnerEvent"
"project_ii::data::generators::excel_generator.dart::ExcelGenerator" <|-- "project_ii::blocs::info_page_bloc.dart::ModifyOwnerEvent"

class "project_ii::blocs::info_page_bloc.dart::ModifyCatEvent" {
  +String? weightRank
  +String? name
  +String? species
  +String? physicalCondition
  +String? appearance
  +String? gender
  +Uint8List? image
  +int? age
  +int? sterilization
  +int? vaccination
  +double? weight
}

"project_ii::blocs::info_page_bloc.dart::ModifyCatEvent" o-- "dart::typed_data::Uint8List"
"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::ModifyCatEvent"

class "project_ii::blocs::info_page_bloc.dart::ModifyOrderEvent" {
  +List<Addition>? additionsList
  +DateTime? checkIn
  +DateTime? checkOut
  +String? attention
  +String? note
  +String? roomID
  +int? eatingRank
  +int? subRoomNum
}

"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::ModifyOrderEvent"

class "project_ii::blocs::info_page_bloc.dart::SaveChangesEvent" {
  +BuildContext context
}

"project_ii::blocs::info_page_bloc.dart::SaveChangesEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::SaveChangesEvent"

class "project_ii::blocs::info_page_bloc.dart::CancelOrderEvent" {
  +BuildContext context
}

"project_ii::blocs::info_page_bloc.dart::CancelOrderEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::CancelOrderEvent"

class "project_ii::blocs::info_page_bloc.dart::CheckoutEvent" {
  +BuildContext context
}

"project_ii::blocs::info_page_bloc.dart::CheckoutEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::CheckoutEvent"

class "project_ii::blocs::info_page_bloc.dart::GotoHomePage" {
  +BuildContext context
}

"project_ii::blocs::info_page_bloc.dart::GotoHomePage" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::info_page_bloc.dart::InformationPageEvent" <|-- "project_ii::blocs::info_page_bloc.dart::GotoHomePage"

class "project_ii::blocs::info_page_bloc.dart::InformationState" {
  +GlobalKey<FormState> formKey1
  +GlobalKey<FormState> formKey2
  +GlobalKey<FormState> formKey3
  +bool isEditing1
  +bool isEditing2
  +bool isEditing3
  +Order modifiedOrder
  +Order order
  +List<Object?> props
  +InformationState copyWith()
  +Order modifyOrder()
  +Cat modifyCat()
  +Owner modifyOwner()
}

"project_ii::blocs::info_page_bloc.dart::InformationState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"project_ii::blocs::info_page_bloc.dart::InformationState" o-- "project_ii::model::order_model.dart::Order"
"equatable::src::equatable.dart::Equatable" <|-- "project_ii::blocs::info_page_bloc.dart::InformationState"

class "project_ii::blocs::info_page_bloc.dart::InfoPageBloc" {
  +int ridx
  +int oidx
  +void onTransition()
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::blocs::info_page_bloc.dart::InfoPageBloc"
"project_ii::data::generators::excel_generator.dart::ExcelGenerator" <|-- "project_ii::blocs::info_page_bloc.dart::InfoPageBloc"

abstract class "project_ii::blocs::login_page_bloc.dart::LoginPageEvent" {
}

class "project_ii::blocs::login_page_bloc.dart::ChangeUsernameEvent" {
  +String username
}

"project_ii::blocs::login_page_bloc.dart::LoginPageEvent" <|-- "project_ii::blocs::login_page_bloc.dart::ChangeUsernameEvent"

class "project_ii::blocs::login_page_bloc.dart::ChangePasswordEvent" {
  +String password
}

"project_ii::blocs::login_page_bloc.dart::LoginPageEvent" <|-- "project_ii::blocs::login_page_bloc.dart::ChangePasswordEvent"

class "project_ii::blocs::login_page_bloc.dart::SubmitEvent" {
  +String username
  +String password
}

"project_ii::blocs::login_page_bloc.dart::LoginPageEvent" <|-- "project_ii::blocs::login_page_bloc.dart::SubmitEvent"

class "project_ii::blocs::login_page_bloc.dart::GotoHomePageEvent" {
  +BuildContext context
}

"project_ii::blocs::login_page_bloc.dart::GotoHomePageEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::login_page_bloc.dart::LoginPageEvent" <|-- "project_ii::blocs::login_page_bloc.dart::GotoHomePageEvent"

class "project_ii::blocs::login_page_bloc.dart::RemoveErrDialogEvent" {
}

"project_ii::blocs::login_page_bloc.dart::LoginPageEvent" <|-- "project_ii::blocs::login_page_bloc.dart::RemoveErrDialogEvent"

class "project_ii::blocs::login_page_bloc.dart::LoginState" {
  +AuthenticationState state
  +String username
  +String password
  +GlobalKey<FormState> formKey
  +List<Object?> props
  +LoginState copyWith()
}

"project_ii::blocs::login_page_bloc.dart::LoginState" o-- "project_ii::blocs::login_page_bloc.dart::AuthenticationState"
"project_ii::blocs::login_page_bloc.dart::LoginState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"equatable::src::equatable.dart::Equatable" <|-- "project_ii::blocs::login_page_bloc.dart::LoginState"

class "project_ii::blocs::login_page_bloc.dart::LoginPageBloc" {
  +void onTransition()
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::blocs::login_page_bloc.dart::LoginPageBloc"

class "project_ii::blocs::login_page_bloc.dart::AuthenticationState" {
  +int index
  {static} +List<AuthenticationState> values
  {static} +AuthenticationState unauthenticated
  {static} +AuthenticationState authenticated
  {static} +AuthenticationState authenticating
}

"project_ii::blocs::login_page_bloc.dart::AuthenticationState" o-- "project_ii::blocs::login_page_bloc.dart::AuthenticationState"
"dart::core::Enum" <|-- "project_ii::blocs::login_page_bloc.dart::AuthenticationState"

abstract class "project_ii::blocs::room_page_bloc.dart::RoomPageEvent" {
}

class "project_ii::blocs::room_page_bloc.dart::RequireDataEvent" {
}

"project_ii::blocs::room_page_bloc.dart::RoomPageEvent" <|-- "project_ii::blocs::room_page_bloc.dart::RequireDataEvent"

class "project_ii::blocs::room_page_bloc.dart::AddRoomEvent" {
  +BuildContext context
}

"project_ii::blocs::room_page_bloc.dart::AddRoomEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::room_page_bloc.dart::RoomPageEvent" <|-- "project_ii::blocs::room_page_bloc.dart::AddRoomEvent"

class "project_ii::blocs::room_page_bloc.dart::ModifyRoomEvent" {
  +BuildContext context
}

"project_ii::blocs::room_page_bloc.dart::ModifyRoomEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::room_page_bloc.dart::RoomPageEvent" <|-- "project_ii::blocs::room_page_bloc.dart::ModifyRoomEvent"

class "project_ii::blocs::room_page_bloc.dart::DeleteRoomEvent" {
  +BuildContext context
}

"project_ii::blocs::room_page_bloc.dart::DeleteRoomEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::room_page_bloc.dart::RoomPageEvent" <|-- "project_ii::blocs::room_page_bloc.dart::DeleteRoomEvent"

class "project_ii::blocs::room_page_bloc.dart::CompleteRenderEvent" {
}

"project_ii::blocs::room_page_bloc.dart::RoomPageEvent" <|-- "project_ii::blocs::room_page_bloc.dart::CompleteRenderEvent"

class "project_ii::blocs::room_page_bloc.dart::ChooseRowEvent" {
  +int index
}

"project_ii::blocs::room_page_bloc.dart::RoomPageEvent" <|-- "project_ii::blocs::room_page_bloc.dart::ChooseRowEvent"

class "project_ii::blocs::room_page_bloc.dart::UnchooseRowEvent" {
  +int index
}

"project_ii::blocs::room_page_bloc.dart::RoomPageEvent" <|-- "project_ii::blocs::room_page_bloc.dart::UnchooseRowEvent"

class "project_ii::blocs::room_page_bloc.dart::RefreshEvent" {
}

"project_ii::blocs::room_page_bloc.dart::RoomPageEvent" <|-- "project_ii::blocs::room_page_bloc.dart::RefreshEvent"

class "project_ii::blocs::room_page_bloc.dart::RoomState" {
  +RenderState renderState
  +Set<int> currentIndexes
  +List<Object?> props
  +RoomState copyWith()
}

"project_ii::blocs::room_page_bloc.dart::RoomState" o-- "project_ii::data::types::render_state.dart::RenderState"
"equatable::src::equatable.dart::Equatable" <|-- "project_ii::blocs::room_page_bloc.dart::RoomState"

class "project_ii::blocs::room_page_bloc.dart::RoomPageBloc" {
  +void onTransition()
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::blocs::room_page_bloc.dart::RoomPageBloc"

abstract class "project_ii::blocs::service_page_bloc.dart::ServicePageEvent" {
}

class "project_ii::blocs::service_page_bloc.dart::RequireDataEvent" {
}

"project_ii::blocs::service_page_bloc.dart::ServicePageEvent" <|-- "project_ii::blocs::service_page_bloc.dart::RequireDataEvent"

class "project_ii::blocs::service_page_bloc.dart::AddServiceEvent" {
  +BuildContext context
}

"project_ii::blocs::service_page_bloc.dart::AddServiceEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::service_page_bloc.dart::ServicePageEvent" <|-- "project_ii::blocs::service_page_bloc.dart::AddServiceEvent"

class "project_ii::blocs::service_page_bloc.dart::ModifyServiceEvent" {
  +BuildContext context
}

"project_ii::blocs::service_page_bloc.dart::ModifyServiceEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::service_page_bloc.dart::ServicePageEvent" <|-- "project_ii::blocs::service_page_bloc.dart::ModifyServiceEvent"

class "project_ii::blocs::service_page_bloc.dart::DeleteServiceEvent" {
  +BuildContext context
}

"project_ii::blocs::service_page_bloc.dart::DeleteServiceEvent" o-- "flutter::src::widgets::framework.dart::BuildContext"
"project_ii::blocs::service_page_bloc.dart::ServicePageEvent" <|-- "project_ii::blocs::service_page_bloc.dart::DeleteServiceEvent"

class "project_ii::blocs::service_page_bloc.dart::CompleteRenderEvent" {
}

"project_ii::blocs::service_page_bloc.dart::ServicePageEvent" <|-- "project_ii::blocs::service_page_bloc.dart::CompleteRenderEvent"

class "project_ii::blocs::service_page_bloc.dart::ChooseRowEvent" {
  +int index
}

"project_ii::blocs::service_page_bloc.dart::ServicePageEvent" <|-- "project_ii::blocs::service_page_bloc.dart::ChooseRowEvent"

class "project_ii::blocs::service_page_bloc.dart::UnchooseRowEvent" {
  +int index
}

"project_ii::blocs::service_page_bloc.dart::ServicePageEvent" <|-- "project_ii::blocs::service_page_bloc.dart::UnchooseRowEvent"

class "project_ii::blocs::service_page_bloc.dart::RefreshEvent" {
}

"project_ii::blocs::service_page_bloc.dart::ServicePageEvent" <|-- "project_ii::blocs::service_page_bloc.dart::RefreshEvent"

class "project_ii::blocs::service_page_bloc.dart::ServiceState" {
  +RenderState renderState
  +Set<int> currentIndexes
  +List<Object?> props
  +ServiceState copyWith()
}

"project_ii::blocs::service_page_bloc.dart::ServiceState" o-- "project_ii::data::types::render_state.dart::RenderState"
"equatable::src::equatable.dart::Equatable" <|-- "project_ii::blocs::service_page_bloc.dart::ServiceState"

class "project_ii::blocs::service_page_bloc.dart::ServicePageBloc" {
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::blocs::service_page_bloc.dart::ServicePageBloc"

abstract class "project_ii::blocs::statistic_page_bloc.dart::StatisticPageEvent" {
}

class "project_ii::blocs::statistic_page_bloc.dart::RequireDataEvent" {
}

"project_ii::blocs::statistic_page_bloc.dart::StatisticPageEvent" <|-- "project_ii::blocs::statistic_page_bloc.dart::RequireDataEvent"

class "project_ii::blocs::statistic_page_bloc.dart::CompleteRenderEvent" {
}

"project_ii::blocs::statistic_page_bloc.dart::StatisticPageEvent" <|-- "project_ii::blocs::statistic_page_bloc.dart::CompleteRenderEvent"

class "project_ii::blocs::statistic_page_bloc.dart::RefreshEvent" {
}

"project_ii::blocs::statistic_page_bloc.dart::StatisticPageEvent" <|-- "project_ii::blocs::statistic_page_bloc.dart::RefreshEvent"

class "project_ii::blocs::statistic_page_bloc.dart::StatisticState" {
  +RenderState renderState
  +List<Object?> props
  +StatisticState copyWith()
}

"project_ii::blocs::statistic_page_bloc.dart::StatisticState" o-- "project_ii::data::types::render_state.dart::RenderState"
"equatable::src::equatable.dart::Equatable" <|-- "project_ii::blocs::statistic_page_bloc.dart::StatisticState"

class "project_ii::blocs::statistic_page_bloc.dart::StatisticPageBloc" {
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::blocs::statistic_page_bloc.dart::StatisticPageBloc"

class "project_ii::data::dependencies::internal_storage.dart::InternalStorage" {
  -Map<String, BehaviorSubject<dynamic>> _storage
  {static} +void init()
  +dynamic read()
  +ValueStream<dynamic>? expose()
  +void write()
  +void remove()
}

abstract class "project_ii::data::generators::excel_generator.dart::ExcelGenerator" {
  +dynamic createGuestList()
  +DateTime ignoreHour()
  +String getStringFromServiceForPart1()
  +String getStringFromServiceForPart2()
  +String getStringFromServiceForPart3()
  +dynamic createBill()
}

class "project_ii::data::providers::booking_related_work_provider.dart::BookingRelatedWorkProvider" {
  {static} +dynamic sendOrderInfo()
}

class "project_ii::data::providers::calendar_related_work_provider.dart::CalendarRelatedWorkProvider" {
  +DateTime currentMonth
  +DateTime today
  +bool isInCurrentMonth()
  +dynamic createDisplayListForOneRoom()
  +dynamic getOrdersForOneRoom()
  +dynamic getRoomGroups()
  {static} +void clearRoomGroupsList()
}

class "project_ii::data::providers::history_related_work_provider.dart::HistoryRelatedWorkProvider" {
  {static} +dynamic getHistoriesList()
  {static} +void clearHistoriesList()
}

class "project_ii::data::providers::info_related_work_provider.dart::InfoRelatedWorkProvider" {
  {static} +dynamic saveChanges()
  {static} +dynamic checkout()
  {static} +dynamic cancel()
}

class "project_ii::data::providers::login_related_work_provider.dart::LoginRelatedWorkProvider" {
  {static} +dynamic authenticate()
  {static} +dynamic logout()
}

class "project_ii::data::providers::room_related_work_provider.dart::RoomRelatedWorkProvider" {
  {static} +dynamic getRoomsList()
  {static} +dynamic add()
  {static} +dynamic delete()
  {static} +dynamic modify()
}

class "project_ii::data::providers::service_related_work_provider.dart::ServiceRelatedWorkProvider" {
  {static} +dynamic getServicesList()
  {static} +dynamic add()
  {static} +dynamic delete()
  {static} +dynamic modify()
  {static} +void clearServicesList()
}

class "project_ii::data::providers::statistic_related_work_provider.dart::StatisticRelatedWorkProvider" {
  {static} +dynamic getStatistic()
  {static} +void clearStatistic()
}

class "project_ii::data::types::pair.dart::Pair" {
  +int first
  +int second
}

class "project_ii::data::types::render_state.dart::RenderState" {
  +int index
  {static} +List<RenderState> values
  {static} +RenderState rendering
  {static} +RenderState completed
  {static} +RenderState waiting
  {static} +RenderState hidden
}

"project_ii::data::types::render_state.dart::RenderState" o-- "project_ii::data::types::render_state.dart::RenderState"
"dart::core::Enum" <|-- "project_ii::data::types::render_state.dart::RenderState"

class "project_ii::generated::intl::messages_en.dart::MessageLookup" {
  +Map<String, dynamic> messages
  +String localeName
  {static} -Map<String, Function> _notInlinedMessages()
}

"intl::message_lookup_by_library.dart::MessageLookupByLibrary" <|-- "project_ii::generated::intl::messages_en.dart::MessageLookup"

class "project_ii::generated::l10n.dart::S" {
  {static} -S? _current
  {static} +AppLocalizationDelegate delegate
  {static} +S current
  {static} +dynamic load()
  {static} +S of()
  {static} +S? maybeOf()
}

"project_ii::generated::l10n.dart::S" o-- "project_ii::generated::l10n.dart::S"
"project_ii::generated::l10n.dart::S" o-- "project_ii::generated::l10n.dart::AppLocalizationDelegate"

class "project_ii::generated::l10n.dart::AppLocalizationDelegate" {
  +List<Locale> supportedLocales
  +bool isSupported()
  +dynamic load()
  +bool shouldReload()
  -bool _isSupported()
}

"flutter::src::widgets::localizations.dart::LocalizationsDelegate" <|-- "project_ii::generated::l10n.dart::AppLocalizationDelegate"

class "project_ii::main.dart::ProjectII" {
  -GoRouter _router
  +Widget build()
}

"project_ii::main.dart::ProjectII" o-- "go_router::src::router.dart::GoRouter"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::main.dart::ProjectII"

class "project_ii::model::addition_model.dart::Addition" {
  +int serviceID
  +String? distance
  +int? quantity
  +DateTime? time
  +Map<String, dynamic> toJson()
}

class "project_ii::model::cat_model.dart::Cat" {
  +int age
  +int sterilization
  +int vaccination
  +double? weight
  +String name
  +String physicalCondition
  +String weightRank
  +String? gender
  +String? species
  +String? appearance
  +Uint8List? image
  +Owner owner
  +Map<String, dynamic> toJson()
  +String sterText()
  +String vaccText()
}

"project_ii::model::cat_model.dart::Cat" o-- "dart::typed_data::Uint8List"
"project_ii::model::cat_model.dart::Cat" o-- "project_ii::model::owner_model.dart::Owner"

class "project_ii::model::history_model.dart::History" {
  +int id
  +String action
  +String perfomer
  +String time
  +String details
}

class "project_ii::model::order_model.dart::Order" {
  +DateTime date
  +DateTime checkIn
  +DateTime checkOut
  +Room room
  +Cat cat
  +String inCharge
  +String? note
  +String? attention
  +int subRoomNum
  +int eatingRank
  +int billNum
  +List<Addition>? additionsList
  +bool isOut
  +Map<String, dynamic> toJson()
  +String getBookingInfoToString()
}

"project_ii::model::order_model.dart::Order" o-- "project_ii::model::room_model.dart::Room"
"project_ii::model::order_model.dart::Order" o-- "project_ii::model::cat_model.dart::Cat"

class "project_ii::model::owner_model.dart::Owner" {
  +String name
  +String gender
  +String tel
  +Map<String, String> toJson()
}

class "project_ii::model::room_group_model.dart::RoomGroup" {
  +Room room
  +List<Order> ordersList
  +List<List<Pair>> displayArray
}

"project_ii::model::room_group_model.dart::RoomGroup" o-- "project_ii::model::room_model.dart::Room"

class "project_ii::model::room_model.dart::Room" {
  +String id
  +String type
  +double price
  +int total
  +Map<String, dynamic> toJson()
  +String getRoomDataToString()
}

class "project_ii::model::service_model.dart::Service" {
  +int id
  +String name
  +double price
  +bool distanceNeed
  +bool quantityNeed
  +bool timeNeed
  +Map<String, dynamic> toJson()
}

class "project_ii::model::statistic_model.dart::Statistic" {
  +List<RoomIncome> roomIncome
  +Map<String, int> allOrderNum
  +List<ServiceUsage> serviceUsage
  +Map<String, int> eatingRank
}

class "project_ii::model::statistic_model.dart::RoomIncome" {
  +String roomID
  +double room
  +double service
  +int completedOrderNum
  {static} +RoomIncome createSum()
}

class "project_ii::model::statistic_model.dart::ServiceUsage" {
  +int serviceID
  +double num
  +double percentage
}

class "project_ii::utils::reusables::date_time_picker.dart::DateTimePicker" {
  +String title
  +String? Function(DateTime?)? validator
  +void Function(DateTime?)? onSaved
  +void Function(DateTime?)? onChanged
  +DateTime? initialValue
  +bool? enabled
  +Widget build()
  -void _exec()
}

"project_ii::utils::reusables::date_time_picker.dart::DateTimePicker" o-- "null::String Function(DateTime)"
"project_ii::utils::reusables::date_time_picker.dart::DateTimePicker" o-- "null::void Function(DateTime)"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::utils::reusables::date_time_picker.dart::DateTimePicker"

class "project_ii::utils::reusables::date_time_picker.dart::_Displayer" {
  +String? Function(String?)? validator
  +String title
  +TextEditingController controller
  +bool? enabled
  +Widget build()
}

"project_ii::utils::reusables::date_time_picker.dart::_Displayer" o-- "null::String Function(String)"
"project_ii::utils::reusables::date_time_picker.dart::_Displayer" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::utils::reusables::date_time_picker.dart::_Displayer"

class "project_ii::utils::reusables::image_picker.dart::ImagePicker" {
  +void Function(Uint8List?)? onChanged
  +void Function(Uint8List?)? onSaved
  +double? width
  +double? height
  +Widget? initialWidget
  +Widget build()
  -void _exec()
}

"project_ii::utils::reusables::image_picker.dart::ImagePicker" o-- "null::void Function(Uint8List)"
"project_ii::utils::reusables::image_picker.dart::ImagePicker" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::utils::reusables::image_picker.dart::ImagePicker"

class "project_ii::utils::reusables::location_picker.dart::LocationPicker" {
  +void Function(String?)? onSaved
  +void Function(String?)? onChanged
  +String? initialValue
  +bool? enabled
  +Widget build()
}

"project_ii::utils::reusables::location_picker.dart::LocationPicker" o-- "null::void Function(String)"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::utils::reusables::location_picker.dart::LocationPicker"

abstract class "project_ii::utils::reusables::location_picker.dart::_LocationPickerEvent" {
}

class "project_ii::utils::reusables::location_picker.dart::_ChangeTextEvent" {
  +String? text
}

"project_ii::utils::reusables::location_picker.dart::_LocationPickerEvent" <|-- "project_ii::utils::reusables::location_picker.dart::_ChangeTextEvent"

class "project_ii::utils::reusables::location_picker.dart::_LocationState" {
  +TextEditingController controller
  +String text
  +List<Object?> props
  +_LocationState copyWith()
}

"project_ii::utils::reusables::location_picker.dart::_LocationState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"equatable::src::equatable.dart::Equatable" <|-- "project_ii::utils::reusables::location_picker.dart::_LocationState"

class "project_ii::utils::reusables::location_picker.dart::_LocationPickerBloc" {
}

"bloc::src::bloc.dart::Bloc" <|-- "project_ii::utils::reusables::location_picker.dart::_LocationPickerBloc"

class "project_ii::utils::reusables::location_picker.dart::_MyGoogleMaps" {
  +State<_MyGoogleMaps> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "project_ii::utils::reusables::location_picker.dart::_MyGoogleMaps"

class "project_ii::utils::reusables::location_picker.dart::_MyGoogleMapsState" {
  -Completer<GoogleMapController> _mapController
  -MarkerController _markerController
  -String _searchLocation
  +Widget build()
}

"project_ii::utils::reusables::location_picker.dart::_MyGoogleMapsState" o-- "dart::async::Completer<GoogleMapController>"
"project_ii::utils::reusables::location_picker.dart::_MyGoogleMapsState" o-- "project_ii::utils::reusables::location_picker.dart::MarkerController"
"flutter::src::widgets::framework.dart::State" <|-- "project_ii::utils::reusables::location_picker.dart::_MyGoogleMapsState"

class "project_ii::utils::reusables::location_picker.dart::MarkerController" {
  +Map<MarkerId, Marker> markersList
  +void addMarker()
}

class "project_ii::utils::reusables::location_picker.dart::InfoFetcher" {
  {static} +dynamic calculate()
}

class "project_ii::utils::reusables::notice_dialog.dart::NoticeDialog" {
  {static} +dynamic showErrDialog()
  {static} +dynamic showMessageDialog()
  {static} +dynamic showCheckoutDialog()
}

class "project_ii::utils::reusables::room_info_dialog.dart::RoomInfoDialog" {
  +GlobalKey<FormState> formKey
  +String title
  +Room? initialValue
  +dynamic showRoomInfoDialog()
}

"project_ii::utils::reusables::room_info_dialog.dart::RoomInfoDialog" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"project_ii::utils::reusables::room_info_dialog.dart::RoomInfoDialog" o-- "project_ii::model::room_model.dart::Room"

class "project_ii::utils::reusables::room_info_dialog.dart::_RoomInfoForm" {
  +Room? initialValue
  +GlobalKey<FormState> formKey
  +String title
  +TextEditingController roomID
  +TextEditingController roomType
  +TextEditingController roomPrice
  +TextEditingController roomTotal
  +Widget build()
  +void save()
  +void cancel()
}

"project_ii::utils::reusables::room_info_dialog.dart::_RoomInfoForm" o-- "project_ii::model::room_model.dart::Room"
"project_ii::utils::reusables::room_info_dialog.dart::_RoomInfoForm" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"project_ii::utils::reusables::room_info_dialog.dart::_RoomInfoForm" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::utils::reusables::room_info_dialog.dart::_RoomInfoForm"

class "project_ii::utils::reusables::service_chooser.dart::AdditionChooser" {
  +List<Addition>? initialValue
  +void Function(List<Addition>?)? onSaved
  +void Function(List<Addition>?)? onChanged
  +DateTime checkIn
  +DateTime checkOut
  +bool? alwaysEnabled
  +Widget build()
  -void _exec()
  -Map<String, dynamic> _generateJson()
  -bool _enable()
}

"project_ii::utils::reusables::service_chooser.dart::AdditionChooser" o-- "null::void Function(List<Addition>)"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::utils::reusables::service_chooser.dart::AdditionChooser"

class "project_ii::utils::reusables::service_info_dialog.dart::ServiceInfoDialog" {
  +GlobalKey<FormState> formKey
  +String title
  +Service? initialValue
  +dynamic showServiceInfoDialog()
}

"project_ii::utils::reusables::service_info_dialog.dart::ServiceInfoDialog" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"project_ii::utils::reusables::service_info_dialog.dart::ServiceInfoDialog" o-- "project_ii::model::service_model.dart::Service"

class "project_ii::utils::reusables::service_info_dialog.dart::_ServiceInfoForm" {
  +Service? initialValue
  +GlobalKey<FormState> formKey
  +String title
  +State<_ServiceInfoForm> createState()
}

"project_ii::utils::reusables::service_info_dialog.dart::_ServiceInfoForm" o-- "project_ii::model::service_model.dart::Service"
"project_ii::utils::reusables::service_info_dialog.dart::_ServiceInfoForm" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "project_ii::utils::reusables::service_info_dialog.dart::_ServiceInfoForm"

class "project_ii::utils::reusables::service_info_dialog.dart::_ServiceInfoFormState" {
  +TextEditingController serviceName
  +TextEditingController servicePrice
  +bool d_need
  +bool q_need
  +bool t_need
  +Widget build()
  +void save()
  +void cancel()
}

"project_ii::utils::reusables::service_info_dialog.dart::_ServiceInfoFormState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "project_ii::utils::reusables::service_info_dialog.dart::_ServiceInfoFormState"

class "project_ii::utils::validators::validators.dart::Validators" {
  +DateTime? checkIn
  +DateTime? checkOut
  +String? weightRank
  +String? Function(String?)? usernameValidator
  +String? Function(String?)? passwordValidator
  +String? Function(Object?)? notNullValidator
  +String? Function(DateTime?)? checkInValidator
  +String? Function(DateTime?)? checkOutValidator
  +String? Function(String?)? multilineTextCanNullValidator
  +String? Function(String?)? multilineTextCanNotNullValidator
  +String? Function(String?)? nameValidator
  +String? Function(String?)? speciesValidator
  +String? Function(String?)? weightValidator
  +String? Function(String?)? intValidator
  +String? Function(String?)? telValidator
  +String? Function(DateTime?)? additionsTimeValidator
}

"project_ii::utils::validators::validators.dart::Validators" o-- "null::String Function(String)"
"project_ii::utils::validators::validators.dart::Validators" o-- "null::String Function(Object)"
"project_ii::utils::validators::validators.dart::Validators" o-- "null::String Function(DateTime)"

class "project_ii::view::booking_page_view.dart::BookingPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::booking_page_view.dart::BookingPage"

class "project_ii::view::booking_page_view.dart::Form3" {
  +InternalStorage internalStorage
  +Widget build()
}

"project_ii::view::booking_page_view.dart::Form3" o-- "project_ii::data::dependencies::internal_storage.dart::InternalStorage"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::booking_page_view.dart::Form3"

class "project_ii::view::booking_page_view.dart::Form2" {
  +InternalStorage internalStorage
  +Widget build()
}

"project_ii::view::booking_page_view.dart::Form2" o-- "project_ii::data::dependencies::internal_storage.dart::InternalStorage"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::booking_page_view.dart::Form2"

class "project_ii::view::booking_page_view.dart::Form1" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::booking_page_view.dart::Form1"

class "project_ii::view::calendar_page_view.dart::CalendarPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::calendar_page_view.dart::CalendarPage"

class "project_ii::view::calendar_page_view.dart::BookingInfo" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::calendar_page_view.dart::BookingInfo"

class "project_ii::view::calendar_page_view.dart::DisplayTable" {
  +int rid
  +Widget build()
  +Pair getDisplayValue()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::calendar_page_view.dart::DisplayTable"

class "project_ii::view::calendar_page_view.dart::Cell" {
  +int rid
  +int index
  +int oid
  +Widget build()
  +bool isBeforeToday()
  +Pair getDisplayValue()
  +bool isTheEndOfABooking()
  +bool isTheBeginningOfABooking()
  +bool isSuitableForText()
  +int getNumberOfNights()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::calendar_page_view.dart::Cell"

class "project_ii::view::calendar_page_view.dart::HalfCell" {
  +int rid
  +int index
  +int oid
  +Widget build()
  +bool isBeforeToday()
  +Pair getDisplayValue()
  +bool isTheEndOfABooking()
  +bool isTheBeginningOfABooking()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::calendar_page_view.dart::HalfCell"

class "project_ii::view::history_page_view.dart::HistoryPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::history_page_view.dart::HistoryPage"

class "project_ii::view::home_page_view.dart::HomePage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::home_page_view.dart::HomePage"

class "project_ii::view::info_page_view.dart::InfoPage" {
  +int ridx
  +int oidx
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::info_page_view.dart::InfoPage"

class "project_ii::view::info_page_view.dart::StatusInfo" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::info_page_view.dart::StatusInfo"

class "project_ii::view::info_page_view.dart::CatInfo" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::info_page_view.dart::CatInfo"

class "project_ii::view::info_page_view.dart::OwnerInfo" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::info_page_view.dart::OwnerInfo"

class "project_ii::view::info_page_view.dart::OrderInfo" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::info_page_view.dart::OrderInfo"

class "project_ii::view::login_page_view.dart::LoginPage" {
  +OverlayEntry loadingEntry
  -TextEditingController _usernameController
  -TextEditingController _passwordController
  +Widget build()
}

"project_ii::view::login_page_view.dart::LoginPage" o-- "flutter::src::widgets::overlay.dart::OverlayEntry"
"project_ii::view::login_page_view.dart::LoginPage" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::login_page_view.dart::LoginPage"

class "project_ii::view::login_page_view.dart::UsernameInput" {
  +TextEditingController usernameController
  +Widget build()
}

"project_ii::view::login_page_view.dart::UsernameInput" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::login_page_view.dart::UsernameInput"

class "project_ii::view::login_page_view.dart::PasswordInput" {
  +TextEditingController passwordController
  +Widget build()
}

"project_ii::view::login_page_view.dart::PasswordInput" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::login_page_view.dart::PasswordInput"

class "project_ii::view::room_page_view.dart::RoomPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::room_page_view.dart::RoomPage"

class "project_ii::view::service_page_view.dart::ServicePage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::service_page_view.dart::ServicePage"

class "project_ii::view::statistic_page_view.dart::StatisticPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "project_ii::view::statistic_page_view.dart::StatisticPage"


@enduml